config/routes.rb
Rails.application.routes.draw do
  namespace :api do 
    namespace :v1 do
      post 'authenticate', to: 'authentication#create'
      resources :users, only: [:index, :show, :create, :destroy] do
        resources :posts, only: [:index] do 
          resources :comments, only: [:index,:create]
        end
      end

      resources :posts, only: [] do
        resources :comments, only: [:create]
      end
    end
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, except: [:update] do
    resources :comments, except: [:update]
    resources :likes, only: [:create, :destroy]
  end
  end
  # get "/users/:id/posts/:id/new" => "comments#new", as: 'new_user_post_comment'
  # post "/users/:id/posts/:id" => "comments#create", as: 'user_post_comments'
  # post "/users/:id/posts/:id/likes" => "likes#create", as: 'user_post_likes'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < AuthenticationController
      def index
        @users = User.all
        render json: @users
      end

      def create
        @user = User.new(user_params)

        if @user.save
          render json: @user, status: :created
        else
          render json: @user.errors, status: :unprocessable_entity
        end
      end

      def user_params
        params.permit(:name, :email, :bio, :photo, :password, :password_confirmation)
      end

      def show
        @user = User.find(params[:id])
        render json: @user
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.valid?
      @user.save
      redirect_to users_path
    else
      redirect_to new_users_path
    end
  end

  def edit
    @user = current_user
  end

  def update
    respond_to? do |format|
      if current_user.update(user_params)
        format.html { redirect_to user_path(current_user), notice: 'User was successfully updated.' }
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/users/index.html.erb
<section>
<% @users.each do |user| %>
    <%= link_to user_path(user.id) do %>
        <div class="user">
          <div>
            <img src="<%= user.photo %>" />
          </div>
          <div>
            <h1><%= user.name %></h1>
            <p>Number of posts: <%= user.posts_counter || 0 %></p>
          </div>
        </div>
    <% end %>
<% end %>
<%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }%>

</section>

app/views/users/show.html.erb
<section class="users-show">
    <div>
        <img src="<%= @user.photo %>" />
        <h1><%= @user.name %></h1>
        <p>Number of posts:<%= @user.posts_counter || 0 %></p>
        <p><%= @user.bio %></p>
    </div>

    <div>
    <% @user.recent_posts.each do |post| %>
    <%= link_to user_post_path(@user, post.id) do %>
        <div class="posts">
            <h1>Post: <%= post.title %></h1>
            <p><%= post.text %></p>
            <div>
            <span>Comments:<%= post.comments_counter || 0%></span>
            <span>Likes:<%= post.likes_counter || 0%></span>
            </div>
          </div>
    <% end %>
<% end %>
<button><%=link_to "See all posts", user_posts_path(@user) %></button>
    </div>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
</section>