config/routes.rb
Rails.application.routes.draw do
  namespace :api do 
    namespace :v1 do
      post 'authenticate', to: 'authentication#create'
      resources :users, only: [:index, :show, :create, :destroy] do
        resources :posts, only: [:index] do 
          resources :comments, only: [:index,:create]
        end
      end

      resources :posts, only: [] do
        resources :comments, only: [:create]
      end
    end
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, except: [:update] do
    resources :comments, except: [:update]
    resources :likes, only: [:create, :destroy]
  end
  end
  # get "/users/:id/posts/:id/new" => "comments#new", as: 'new_user_post_comment'
  # post "/users/:id/posts/:id" => "comments#create", as: 'user_post_comments'
  # post "/users/:id/posts/:id/likes" => "likes#create", as: 'user_post_likes'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, foreign_key: 'post_id', dependent: :destroy
  has_many :likes, foreign_key: 'post_id', dependent: :destroy

  after_save :update_posts_counter
  before_destroy :update_posts_down

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def update_posts_down
    author.update_columns('posts_counter' => author.posts_counter - 1)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < AuthenticationController
      before_action :fetch_user, only: %i[index show]
      before_action :authorize_request

      def index
        @posts = current_user ? current_user.posts.includes(:comments) : Post.includes(:comments)
        render json: @posts
      end

      private

      def fetch_user
        @user = User.find(params[:user_id])
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes([:author])
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.author
    @comments = @post.comments.includes([:author])
  end

  def new
    @id = current_user.id
    @post = Post.new
  end

  def create
    post = Post.new(title: post_params[:title], text: post_params[:text], author: current_user)
    flash[:notice] = if post.save
                       'Post created successfully'
                     else
                       'Error'
                     end
    redirect_to user_posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/edit.html.erb
<%= render "form", post:@post %>

app/views/posts/index.html.erb
<h1>Posts index</h1>

<section>
    <div>
        <img src="<%= @user.photo %>" />
        <h1><%= @user.name %></h1>
        <p>Number of posts:<%= @user.posts_counter || 0 %></p>
    </div>

<% @posts.each do |post| %>
  <%= link_to user_post_path(@user, post) do %>
  <h2>Post: <%= post.id %></h2>
  <% end %>
  <div>
    <p><%= post.text %></p>

    <div>
      <span>Comments: <%= post.comments_counter %></span>
      <span>Likes: <%= post.likes_counter %></span>
    </div>
  </div>
  <ul>
  <% if can? :destroy, Post %>

  <li><%= button_to "del", user_post_path(post.author, post.id), method: :delete  %></li>
  <%end%>
</ul>
<% end %>
<%= link_to new_user_post_path do %>Add post<% end %>

<button>Pagination</button>
</section>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with model: @post, url:  user_posts_url, method: :post, local: true do |f| %>
<div>
  <%= f.label :Post_title, require: true %><br>
  <%= f.text_field :title %>
</div>
<div>
  <%= f.label :Enter_Text %><br>
  <%= f.text_area :text, rows: 10, require: true %>  
</div>
<% @post.errors.full_messages_for(:title).each do |message| %>
  <div><%= message %></div>
<% end %>
<div>
  <%= f.submit "Create Post" %>
</div>

<% end %>

app/views/posts/show.html.erb
<h1>I am here</h1>

<section>
      <div class= "posts-container">

        <h1 class="post"><%= @post.title %></h1>
        <div class="posts">
          <span class="posts-comment">Number of comments: <%= @post.comments_counter || 0 %></span>
          <span class="posts-likes">Number of likes: <%= @post.likes_counter || 0 %></span>
        </div>
            <p>post description: <span><%= @post.text%></span> </p>
      </div>
      <div class="recent-comments">
      <ul>
      <% @post.recent_comments.each do |comment| %>
      <li>comments:<%= comment.text %></li>
      <%=link_to "delete comment", user_post_comment_path(comment.author, comment.post, comment), method: :delete, data: { turbo_method: :delete }  %>
       <% end %>
       <%= link_to 'Add comment', new_user_post_comment_path(@user, @post) %>
       <%= form_with url: "/users/#{@post.author_id}/posts/#{@post.id}/likes", scope: :like do |f| %>
  <%= f.submit " Add Like" %>
  <% end %>
      </ul>
      </div>
</section>